version: '3.8'

services:
  pass_vault:
    build: ./backend
    ports:
      - 8000
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/postgres
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1G"
  
  nginx:
    build: ./nginx
    ports:
      - 8888:80
    restart: unless-stopped
    depends_on:
      - pass_vault
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1G"

  db:
    image: postgres:12
    volumes:
        - ./db/db_data:/var/lib/postgresql/data
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "1G"
